title: "Ajayi Oluwaseyi | Data Analyst Portfolio"
description: "Transforming Data into Actionable Insights — Power BI | SQL | Excel | Python"
theme: jekyll-theme-cayman

# Personal details
name: "Ajayi Oluwaseyi"
email: "oluwaseyi1414@gmail.com"
linkedin: "https://www.linkedin.com/in/ajayi-oluwaseyi-865a35248"
twitter: "https://twitter.com/Psychizzy1414"
phone: "+2349035283723"

show_downloads: false
google_analytics:

